<?php if (count($this->messages)) : ?>
	<div align="center" style="margin: 100px auto;">
		<ul id="messages">
			<?php foreach ($this->messages as $message) : ?>
	    		<li><?php echo $this->escape($message); ?></li>
			<?php endforeach; ?>
		</ul>
	</div>
<?php else: ?>
	<div class="usePageDetail">
		<div class="usePageTitle">
			<h3><?= $this->product->title ?></h3>
		</div>
		<div class="usePageContent">
			<div id="UiContentDetail">
				<div class="useLeftColumn">
					<div class="useProduct">
						<div class="UiDisplay" style="text-align: center;">
							<? 
							
								if($this->contentDetail->has_image_high)
								{
									//Monta a url do arquivo
									$filename = BASE_ROOT . $this->contentDetail->folderpath .'/alta/'. $this->contentDetail->filename;
								}
								else{
									//Monta a url do arquivo
									$filename = BASE_ROOT . $this->contentDetail->folderpath .'/'. $this->contentDetail->filename;
								}
								echo  $this->preview;
							?>
						</div>
						<div class="UiDetailWrap">
							<div class="UiDetail">
								<div class="UiTitle">
									<span><?= UseZF_Util::useTruncate($this->contentDetail->title, 30) ?></span>
									<div class="UiDetail">
										<? if($this->contentDetail->resource_type == 'IMG' && !empty($this->contentDetail->resolution)): ?>
											Resolução <?= $this->contentDetail->resolution ?> | 
										<? endif; ?>
										Tamanho do arquivo <?= UseZF_Util::useFileSize($this->contentDetail->filesize) ?>
									</div>
								</div>
							</div>
							<!-- Vertical Scroll descricao -->	
							<div class="UiDescriptionWrap">
								<div class="UiDescription">
									<div class="VScrollbar">
										<div class="scrollbar">
											<div class="track">
												<div class="thumb">
													<div class="end"></div>
												</div>
											</div>
										</div>
										<div class="viewport">
											<div class="overview">
												<span>
													<?= $this->contentDetail->description ?>
												</span>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="useRightColumn">
					<table width="100%" height="600" border="0">
						<tr>
							<td>
								<a href="<?= $this->baseUrl .'/download.php?url='. $filename ?>"><img style="cursor:pointer;" alt="" src="<?= $this->useDefault->images?>/bt/btBaixarAgora.png"/></a>
							</td>
						</tr>
					</table>
				</div>
				<div class="useClear"></div>
			</div>
		</div>
	</div>
	<br />
<?php endif; ?>