<div class="UiLogo">
	<div class="UiWrap">
		<div class="UiContent">
			<div class="UiTitle">
				Informe o endereço de e-mail cadastrado para recuperar a senha
			</div>
			<div>
				<form action="forgotpassword" method="post">
					<div class="UiElement">
						<div class="UiSubTitle">
							E-MAIL:
						</div>
						<input class="UiLoginText" type="text" name="user_email" />
					</div>
					<div class="UiLink">
						<a href="<?= $this->baseUrl ?>/login">Login</a>
					</div>
					<? if(!empty($this->message)): ?>
						<div class="UiLink">
							<span><?= $this->message ?></span>
						</div>
					<? endif;?>
					<div class="UiButton">
						<input type="image" name="Entrar" src="<?= $this->useDefault->images ?>/bt/btEntrar.gif" />
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<div class="UiFooter">
	<div class="UiShadow">
		<p>
			Parceiros LG - Todos os direitos estão reservados - Copyright 2012 - Desenvolvido por Tobe App
		</p>
	</div>
</div>
