<div class="UiLogo">
	<div class="UiWrap">
		<div class="UiContent">
			<div class="UiTitle">
				Desculpe o transtorno, estamos em Manutenção!
				Em poucos instantes estaremos novamente em funcionamento.
				
			</div>
		</div>
	</div>
	<br />
</div>
<div class="UiFooter">
	<div class="UiShadow">
		<p>
			Parceiros LG - Todos os direitos estão reservados - Copyright 2012 - Desenvolvido por Tobe App
		</p>
	</div>
</div>